version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000" # Express server
      - "24678:24678" # Vite HMR (Hot Module Replacement)
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # Required for Vite HMR to work in Docker
      - VITE_HOST=0.0.0.0
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/keys"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
